#!/usr/bin/env node
// Tariff Exposure Monitor — stateless HTTPS endpoint for Voidnet.
//
// Written to Voidnet's publisher contract (docs.openvoidnet.com/docs/publisher-guide/mcp,
// read 2026-08-21), which is NOT the same protocol the stdio server speaks:
//   - MCP 2026-07-28, STATELESS. No initialize handshake, no sessions, no GET/DELETE.
//   - One endpoint, /mcp, handling every method.
//   - server/discover replaces initialize.
//   - Authorization: Bearer <publisher key> validated on EVERY request; 401 otherwise.
//   - MCP-Protocol-Version header must match _meta.protocolVersion in the body (-32020 if not).
//   - Unsupported protocol version -> 400 / -32022.
// TLS is terminated by nginx in front of this process, so it listens on plain HTTP on localhost.
//
// The tools themselves come from src/tools.js — the same code the stdio server runs, so the two
// transports cannot drift apart.
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOOLS, callTool, SERVER_INFO } from './tools.js';

// Read .env ourselves. systemd would do this via EnvironmentFile, but this runs under pm2, which
// does not — and the first deploy silently kept reporting key_configured:false because of it.
// Deliberately does NOT override anything already in the environment.
(() => {
  try {
    const envPath = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '.env');
    for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  } catch { /* no .env is a normal state: the server then fails closed, which is intended */ }
})();

const PORT = Number(process.env.PORT || 8791);
const HOST = process.env.HOST || '127.0.0.1';
const PROTOCOL_VERSION = '2026-07-28';
// Generated by Voidnet Console when the app is published, and shown once. Until it is set this
// server FAILS CLOSED: an endpoint that accepts unauthenticated calls is worse than one that is
// not published yet. VOIDNET_ALLOW_UNAUTH=1 exists only for local smoke tests.
const PUBLISHER_KEY = process.env.VOIDNET_PUBLISHER_KEY || '';
const ALLOW_UNAUTH = process.env.VOIDNET_ALLOW_UNAUTH === '1';

const json = (res, status, body, extra = {}) => {
  const s = JSON.stringify(body);
  res.writeHead(status, { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(s), ...extra });
  res.end(s);
};
const rpcError = (res, status, id, code, message, data) =>
  json(res, status, { jsonrpc: '2.0', id: id ?? null, error: { code, message, ...(data ? { data } : {}) } });

function readBody(req, limit = 1_000_000) {
  return new Promise((resolve, reject) => {
    let n = 0; const chunks = [];
    req.on('data', (c) => { n += c.length; if (n > limit) { reject(new Error('body too large')); req.destroy(); } else chunks.push(c); });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

const server = http.createServer(async (req, res) => {
  // Liveness, for our own monitoring only — not part of the Voidnet contract.
  if (req.method === 'GET' && (req.url === '/health' || req.url === '/mcp/health')) {
    return json(res, 200, { ok: true, server: SERVER_INFO, protocol: PROTOCOL_VERSION,
                            tools: TOOLS.map((t) => t.name), key_configured: !!PUBLISHER_KEY });
  }
  // "No GET/DELETE endpoints" — say so explicitly rather than 404, which reads like a wrong URL.
  if (req.method !== 'POST') {
    return rpcError(res, 405, null, -32600, 'Method Not Allowed',
      'This is a stateless MCP 2026-07-28 endpoint; use POST /mcp.');
  }
  if ((req.url || '').split('?')[0] !== '/mcp') {
    return rpcError(res, 404, null, -32601, 'Not Found', 'The MCP endpoint is POST /mcp.');
  }

  // 1. AUTH FIRST — before parsing, before anything. "If the key is invalid, return 401
  //    immediately — do not process the MCP request."
  const auth = req.headers['authorization'] || '';
  const presented = auth.startsWith('Bearer ') ? auth.slice(7).trim() : '';
  if (!ALLOW_UNAUTH) {
    if (!PUBLISHER_KEY) {
      console.error('[mcp-http] no VOIDNET_PUBLISHER_KEY configured — refusing every request');
      return rpcError(res, 401, null, -32001, 'Unauthorized', 'Server is not configured with a publisher key');
    }
    if (!presented || presented !== PUBLISHER_KEY) {
      return rpcError(res, 401, null, -32001, 'Unauthorized', 'Invalid or missing publisher API key');
    }
  }

  let body;
  try { body = JSON.parse(await readBody(req)); }
  catch (e) { return rpcError(res, 400, null, -32700, 'Parse error', e.message); }

  const id = body?.id ?? null;
  const method = body?.method;

  // 2. Protocol version: the HEADER must be supported, and must MATCH the body's _meta.
  const headerVersion = req.headers['mcp-protocol-version'];
  if (headerVersion && headerVersion !== PROTOCOL_VERSION) {
    return rpcError(res, 400, id, -32022, 'Unsupported protocol version',
      `This server speaks ${PROTOCOL_VERSION}; received ${headerVersion}`);
  }
  const bodyVersion = body?._meta?.protocolVersion;
  if (headerVersion && bodyVersion && headerVersion !== bodyVersion) {
    return rpcError(res, 400, id, -32020, 'HeaderMismatch',
      `MCP-Protocol-Version (${headerVersion}) does not match _meta.protocolVersion (${bodyVersion})`);
  }
  if (bodyVersion && bodyVersion !== PROTOCOL_VERSION) {
    return rpcError(res, 400, id, -32022, 'Unsupported protocol version',
      `This server speaks ${PROTOCOL_VERSION}; body requested ${bodyVersion}`);
  }

  try {
    if (method === 'server/discover') {
      return json(res, 200, { jsonrpc: '2.0', id, result: {
        supportedVersions: [PROTOCOL_VERSION],
        capabilities: { tools: { listChanged: false } },
        serverInfo: SERVER_INFO,
        instructions: 'US import tariff data. Call lookup_hts_code first when you only have a '
          + 'product description, then calculate_tariff with the HTS code and an ISO-2 origin '
          + 'country to get the full stacked rate and the Nov 10 2026 cliff projection.',
      } });
    }
    if (method === 'tools/list') {
      return json(res, 200, { jsonrpc: '2.0', id, result: { tools: TOOLS } });
    }
    if (method === 'tools/call') {
      const name = body?.params?.name;
      if (!name) return rpcError(res, 400, id, -32602, 'Invalid params', 'params.name is required');
      if (!TOOLS.some((t) => t.name === name)) {
        return rpcError(res, 404, id, -32601, 'Unknown tool', `No tool named "${name}"`);
      }
      const result = await callTool(name, body?.params?.arguments || {});
      return json(res, 200, { jsonrpc: '2.0', id, result });
    }
    if (method === 'ping') return json(res, 200, { jsonrpc: '2.0', id, result: {} });
    // Declared unsupported rather than silently empty: a buyer must be able to tell
    // "this server has no resources" from "this server ignored me".
    if (method === 'resources/list') return json(res, 200, { jsonrpc: '2.0', id, result: { resources: [] } });
    if (method === 'prompts/list') return json(res, 200, { jsonrpc: '2.0', id, result: { prompts: [] } });
    if (method === 'initialize') {
      return rpcError(res, 400, id, -32022, 'Unsupported protocol version',
        'This endpoint is stateless MCP 2026-07-28; use server/discover instead of initialize.');
    }
    return rpcError(res, 404, id, -32601, 'Method not found', String(method));
  } catch (e) {
    console.error('[mcp-http] handler error:', e.message);
    return rpcError(res, 500, id, -32603, 'Internal error', e.message);
  }
});

server.listen(PORT, HOST, () => {
  console.log(`[mcp-http] tariffmonitor on http://${HOST}:${PORT}/mcp · protocol ${PROTOCOL_VERSION}`
    + ` · tools: ${TOOLS.map((t) => t.name).join(', ')}`
    + ` · publisher key ${PUBLISHER_KEY ? 'configured' : 'NOT SET (all requests will 401)'}`);
});
